# 
# Classify section does a basic file/object identification
# based on fields in the object
# 
# required paths are those needed to identify an object as belonging
# to a particular data_model
# 
# n3id is the field to be used for unique identification of an
# object in the data store, if empty n3 will assign a unique id.
# 
# links are the features of the object to connect to the 
# overall data graph
# 
# unique fields are those used to construct a unique linking key
# for the object if no suitable single property is available
# 
# 
[[classifier]]
data_model = "SIF"
required_paths = ["*.RefId"]
n3id = "*.RefId"
links = ["RefId","LocalId"]

[[classifier]]
data_model = "XAPI"
required_paths = ["actor.name", "actor.mbox", "object.id", "verb.id"]
n3id = "id"
links = ["actor.mbox","actor.name","object.id","object.definition.name"]

[[classifier]]
data_model = "Syllabus"
required_paths = ["learning_area", "subject", "stage"]
n3id = "id"
links = ["learning_area", "subject", "stage"]
unique = ["subject","stage"]

[[classifier]]
data_model = "Subject"
required_paths = ["Subject.subject", "Subject.synonyms"]
n3id = "id"
links = ["Subject.learning_area", "Subject.subject", "Subject.stage", "Subject.synonyms"]
unique = ["Subject.subject", "Subject.stage"]

[[classifier]]
data_model = "Lesson"
required_paths = ["Lesson.learning_area", "Lesson.lesson_id"]
n3id = "id"
links = ["Lesson.learning_area", "Lesson.subject", "Lesson.stage"]
unique = ["Lesson.subject","Lesson.stage"]

[[classifier]]
data_model = "LessonSequence"
required_paths = ["thearea", "thecourse", "thesubject", "thestage"]
n3id = "lessonId"
links = ["thearea", "thesubject", "thestage"]
unique = ["thesubject","thestage"]

[[classifier]]
data_model = "LessonSchedule"
required_paths = ["thecolor", "thecourse"]
n3id = "scheduleId"
links = ["userId"]

[[classifier]]
data_model = "OtfProviderItem"
required_paths = ["providerNodeId", "externalReference"]
n3id = "providerNodeId"
links = ["externalReference"]

[[classifier]]
data_model = "OtfNLPLink"
required_paths = ["nlpNodeId", "nlpReference"]
n3id = "nlpNodeId"
links = ["linkReference"]

[[classifier]]
data_model = "OtfScale"
required_paths = ["progressionLevel", "partiallyAchieved"]
n3id = "scaleItemId"
links = ["progressionLevel"]